### ISSUE TITLE
[SHF] Import de sites en lot

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/gn_module_cmr#4]
Les campagnes CMR pour la cistude nécessitent de poser de nombreux pièges (>60 dans certains cas) que les opérateurs géolocalisent généralement sur le terrain par gps. Il faudrait pouvoir simplifier la création de nombreux sites à partir d'un import d'un fichier.

Peut-être reprendre la fonctionnalité d'import gpx déjà implémenté et optimiser sont fonctionnement pour pouvoir enchainer la saisie des sites :
- garder le fichier gpx en mémoire
- à chaque enregistrement de site, enchainer sur le site suivant en gardant en mémoire certains paramètres précédents, pouvoir incrémenter le nom avec un numéro et sélectionner automatiquement le point/géométrie suivante pour éviter d'avoir à cliquer sur la carte.

**Comment by camillemonchicourt** [comment]
C'est le cas quand on importe un GPX avec plusieurs points et qu'on enchaîne les relevés dans Occtax : https://github.com/PnX-SI/GeoNature/issues/813

Dans Monitoring, on peut enchaîner les créations de site, donc il faut reprendre le même fonctionnement que dans Occtax.

**Comment by Amegilla** [comment]
Oui, c'est surtout sur le dernier point qu'il y a sans doute des choses à ajouter.

**Comment by camillemonchicourt** [comment]
Il a été retenu d'intégrer le concept d'individus dans le module Monitoring plutôt que de le dupliquer en grande partie dans un module spécifique CMR : https://github.com/PnX-SI/gn_module_monitoring/issues/213
Et un import vers Monitoring va être développé à partir de cette fin d'année.
